### ISSUE TITLE
[FEAT] - Question Of The Day with Becca!

### ISSUE THREAD

**Issue by Vyvy-vi** [nhcarrigan/becca-lyria#1055]
### What feature would you like to see?

A Question Of The Day feature.

It would be really great if the unreliable QOTD bot can be replaced by Becca
:D And that way maybe we can also get more fun questions.

**Comment by nhcarrigan** [comment]
I think we'd need to iron out some implementation approaches. Ideally in a way that will scale.

**Comment by naomi-lgbt** [comment]
Okay,

In order for this to work, we will need to do a few things:

- We will need to add config options to set the channel, and to set the hour for the CRON (in UTC), and optionally a role to ping.
- We will need to load in a bunch of questions.
- We will need to track which questions have been asked in a server. (I don't have an implementation idea for this yet...)

We can probably shove these under a new `qotd` top-level command.

**Comment by j-dogcoder** [comment]
Hey @naomi-lgbt! I'm not sure what your plans are for implementing this, but Heptagram API has a qotd endpoint.

You can find the endpoint [here](https://api.heptagrambotproject.com/v4/qotd/), and the docs are up to date [here](https://api.heptagrambotproject.com/docs/).

Currently the endpoint is **very** simple, but the goal with Heptagram API is to tailor it to bots, so I am happy to change and adapt the endpoint to make it work for this implementation!

Just let me know!!

**Comment by j-dogcoder** [comment]
Just saw that those docs don't have the endpoint 🤦. When I get home tomorrow, I will have those docs updated. The endpoint is currently there tho! You can do a get request on it, and it should return a random one.

**Comment by naomi-lgbt** [comment]
I'd be happy to consider it.

The biggest things are being able to track which questions have already been sent, and servers being able to load custom questions.

**Comment by j-dogcoder** [comment]
Awesome! Re: the docs, they should now be deployed, and up to date. 

What would make the tracking able to happen? Currently a response to the endpoint looks like this
```json 
{
    "_id": "62aa53296e2e5cdfd27bd4b1",
    "id": "c19034ba-9364-4d31-b700-61600a056c18",
    "uniqueID": "90",
    "qotd": "What outdoor activity haven’t you tried, but would like to?",
    "dateUploaded": "2022-05-06T23:00:40.452Z",
    "__v": 0
}
```

It is kind of messy right now, but we can use either _"id"_ or _"uniqueID_ and a new endpoint to be able to specifically call certain questions. _uniqueID_ may make the most sense, because it is sequential, instead of randomly generated.

**Comment by j-dogcoder** [comment]
Let me know what you think, I am open to suggestions, and want to make this as easy as possible for you!

**Comment by j-dogcoder** [comment]
Currently the DB has 351 qotds, but we can expand that significantly.

**Comment by j-dogcoder** [comment]
@naomi-lgbt, what do you think?

**Comment by naomi-lgbt** [comment]
For this to work, we would need:

- Either a way to pass a list of questions that we want to exclude from the random questions OR a way to pull down all the questions at once (so we can do the filter logic locally)
- Assurance that the `uniqueID` will never change when new questions are added.

**Comment by j-dogcoder** [comment]
Hey @naomi-lgbt, I would love to take this on...

**Comment by j-dogcoder** [comment]
> For this to work, we would need:
> 
> * Either a way to pass a list of questions that we want to exclude from the random questions OR a way to pull down all the questions at once (so we can do the filter logic locally)
> * Assurance that the `uniqueID` will never change when new questions are added.

I am working on routes to make those things possible

**Comment by j-dogcoder** [comment]
Is this also blocked until the config overhaul?

**Comment by naomi-lgbt** [comment]
Yes.

**Comment by j-dogcoder** [comment]
I will focus on the API side while I wait then. 😄

**Comment by j-dogcoder** [comment]
Would love to take this once I finish my other issue

**Comment by j-dogcoder** [comment]
@naomi-lgbt, with the API temporarily removed from the scam link detection, would you prefer we don't use it for QOTDs?

**Comment by naomi-lgbt** [comment]
Nah, we can totally use it for QOTDs - this isn't a feature that will result in erroneous kicks/bans so we're all good.

**Comment by j-dogcoder** [comment]
👍🏻

**Comment by j-dogcoder** [comment]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/65788728/198161692-3f9c1656-18b3-40be-b959-607ee52311bb.png">

**Comment by j-dogcoder** [comment]
You can filter out now....

**Comment by j-dogcoder** [comment]
API is all set to go!

**Comment by j-dogcoder** [comment]
The IDs will never change for an QOTD

**Comment by j-dogcoder** [comment]
Loading up the database now, but we have `1505` qotds in there now

**Comment by a2937** [comment]
How much work exists so far regarding this? How do you want it implemented? I was thinking of having Becca retrieve a random question from that Question of the Day API and posting it in the channel the command was ran in. And naturally this command should be only be ran by moderators.

**Comment by jdogcoder** [comment]
Ah! Totally had no idea this was still assigned to me. Heptagram API Has been sunsetted, and all of it's endpoints have been moved to my much more general API. Happy to provide new docs and whatnot if desired, @naomi-lgbt may also want this to be done "in house" at this point.

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
