### ISSUE TITLE
[FEAT] - Conditional role assignment

### ISSUE THREAD

**Issue by Ryltarr** [nhcarrigan/becca-lyria#1385]
### What feature would you like to see?

I couldn't think of a concise way to write it in the title, but this would be a feature to fill a function that I wish Discord had natively: handling users based on a combination of roles, instead of just one by one.

The core working principle would be something like this: bot watches role assignment feed, when an affected role is added it checks if the other role conditions are met, and if so assigns them the appropriate role. See below for some examples.

Examples:
1. User is vetted and should be allowed to access a subset of channels, but may want to opt in/out of them as they see fit.
This could be served by giving the user a role like "Private Channels" and then they could (either through BeccaLyria or another framework) choose which of the channel roles within that they want; however, if "Private Channels" is revoked, they lose access to those other roles... on second thought, that could be managed using conditional opt-in roles in other frameworks.
2. User has been vetted, and has access to some private channels; however, they do not get access to another channel via a separate role until such time as they reach a certain level or otherwise earn another role.

I'm struggling to come up with exacting examples, but I hope this is clear enough.

### Additional information

This would basically emulate being able to assign permissions by Boolean evaluation like Channel A requiring (Role A AND Bole B)

**Comment by naomi-lgbt** [comment]
I think we could bake this into the reaction role functionality - add a config option that allows a server to specify required roles before a reaction role can be claimed.

I'll add this to the v21 roadmap.

**Comment by Ryltarr** [comment]
Was hoping it would be compatible with outside role management systems, since BeccaLyria isn't running anything besides level roles for us at this point in time; but, it's something I suppose.

**Comment by naomi-lgbt** [comment]
We could listen to the `guildMemberUpdate` event, but in our experience it's been notoriously unreliable for checking roles.

**Comment by ieahleen** [comment]
considering the new handling of which channels are shown to the user from user choice, is this something that should be reconsidered/replanned?

**Comment by naomi-lgbt** [comment]
No, onboarding allows you to configure self-selectable channels and roles.

This issue is specifically requesting something that allows for users who obtain one role to be given additional dependent roles automatically.

**Comment by ieahleen** [comment]
Ok, so the thing would be
- user get role A
- the bot assigns role(s) B and C automatically
- and this should be configurable in the `/config`

---

what about 

> We could listen to the `guildMemberUpdate` event, but in our experience it's been notoriously unreliable for checking roles.

is that changed now?

**Comment by naomi-lgbt** [comment]
That is still the case, unfortunately.

And the bot will need to work in the opposite direction as well. If the user *loses* role A, they lose role B and C too.

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
