### ISSUE TITLE
[FEAT] - Improved Image Handling

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1579]
### What feature would you like to see?

Discord has gotten pretty aggressive about purging assets from the CDN when no longer necessary.

We need to fix a couple of things here:

- When a message is deleted and has an image, re-upload the image in the logs instead of sticking it in an embed
- When a user updates their avatar, upload both old and new as attachments in the log message

**Comment by Vyvy-vi** [comment]
I'd like to work on this

**Comment by naomi-lgbt** [comment]
Go for it~!

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
