### ISSUE TITLE
[CHORE] - Tests and Test Coverage

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1734]
### What work needs to be performed?

We need to finish testing out all of Becca's features. There are a few steps here:

- [X] Add code coverage utility
- [ ] Get code coverage to 90% or above - run `test:coverage` to see progress.
  - [ ] Commands will need to use our [testing utility](https://github.com/nhcarrigan/discordjs-testing) which is currently in early alpha development. Contributors are welcome to improve the utility to allow for more thorough testing.
- [ ] Replace the `test` command with the `test:coverage` command and remove the `test:coverage` command.

### Additional information

This is going to be a large and time-consuming process. Contributors are encouraged to make smaller PRs that only target a single file.

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
