### ISSUE TITLE
[FEAT] - `/support faq` command

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1741]
### What feature would you like to see?

We need to add a `/support faq` command. There's a few implementation details here:

- We should maintain a config object of frequently asked questions and responses
- The command should take a question parameter
  - The parameter should use autocomplete and suggest the 5 most similar questions (we can use the string-similarity package)
- The command should find the correct question and respond with the response text (as text, not embed).

### Additional information

There's some implementation details to iron out, but this'll probably be a https://github.com/BeccaLyria/discord-bot/labels/help%20wanted when the ticket is polished.

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
