### ISSUE TITLE
[FEAT] - `/support data-request` command

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1743]
### What feature would you like to see?

We should add a `/support data-request` command. This command should:

- Should fetch the user's record for each of the user-specific data collections:
  - `activities`
  - `currencies`
  - `emotecounts`
  - `messagecounts`
  - `newlevels`
  - `optouts`
  - `starcounts`
  - `userconfigs`
  - `voters`
- Should check if the user is the **guild owner**, and if so, fetch each of the guild-specific data collections:
  - `histories`
  - `polls`
  - `scheduledevents`
  - `servers`
- Should take all fetched data, compile it into a JSON object, and build that object into a Discord attachment
- Should send the attachment, as well a message content explaining that they should join the support server to request data deletion

### Additional information

The JSON should look something like:

```json
{
  activities: [
  {
    userId: "465650873650118659",
    buttons: 128
  }
 ],
 currencies: {}
}
```

Note that models that have a single unique ID (userId or serverId) will be a single object, whereas those with both a unique userId and serverId will be an array of objects.

**Comment by Vyvy-vi** [comment]
I'd like to work on this.

**Comment by naomi-lgbt** [comment]
Go for it!

**Comment by helloimalastair** [comment]
It's been a little while since I've participated here. I'll give this one a spin!
