### ISSUE TITLE
[FEAT] - `userconfig highlight` command

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1745]
### What feature would you like to see?

Late night idea so this ticket probably needs to be fleshed out more but...

Let's add a user config command that allows a user to highlight key words in a message. Implementation details:

- Update the userconfig model to include a `highlights` property
  - Should be an array of objects with a `serverId` key and a `word` key
- User can set a word to be highlighted in a server
- When a message is sent with the highlighted word, ping the user.
- On message create, check if there is a highlight request for any words in that message.

### Additional information

- We may want to cache the configs to avoid a DB call on every message?
- Interested contributors may begin work on this now, but know that the spec may change as we iterate over implementation details.

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
