### ISSUE TITLE
[FEAT] - Convert Activity Context to Ephemeral

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1747]
### What feature would you like to see?

The `activity` context gets accidentally clicked a lot. We should switch the response to be ephemeral.

### Additional information

 This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- In the [activity context](https://github.com/BeccaLyria/discord-bot/blob/main/src/contexts/activity.ts) file:
  - Pass `{ephemeral: true}` to the `interaction.deferReply()` call.

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by MellowMancer** [comment]
This feature already seems to have been solved

**Comment by naomi-lgbt** [comment]
The activity context is [not ephemeral](https://github.com/BeccaLyria/discord-bot/blob/6b862203ab653160f3ed813f3eccdc2eb04a7431/src/contexts/activity.ts#L14) yet, no.

**Comment by ieahleen** [comment]
Considering it has been a bit this was opened, can I take this on, or do you prefer leaving it for first time contributors?

**Comment by naomi-lgbt** [comment]
Go for it!
