### ISSUE TITLE
[FEAT] - Sticky Roles

### ISSUE THREAD

**Issue by naomi-lgbt** [nhcarrigan/becca-lyria#1798]
### What feature would you like to see?

Let's add a config where servers can set sticky roles - when a user leaves, the roles they have which are sticky are stored in a database

If they rejoin, they get the sticky roles back

### Additional information

To ensure user privacy:
- The policy must be updated to indicate the storage of sticky roles
- on member join, if sticky roles are found they should be applied and the record deleted

**Comment by melody-iuvo** [comment]
This project is now in maintenance mode. We will only be providing bug fixes and necessary updates to maintain functionality.
        
If you are still interested in this feature, we offer a couple of options:
- If you would like to implement it yourself, pull requests are still gladly accepted. We are just not building features ourselves.
- Or, if you prefer for us to build it anyway, you are welcome to fill out a commission form [in our Discord server](https://chat.nhcarrigan.com)
