### ISSUE TITLE
[BUG] - fix poll duration description

### ISSUE THREAD

**Issue by helloimalastair** [nhcarrigan/becca-lyria#1888]
### What bug did you encounter?

`/community poll`'s [*duration*](https://github.com/BeccaLyria/discord-bot/blob/a4bc832a7e295623ec3f3e44c47b2f0643ab424f/src/commands/community.ts#L175) field contains the description:
> The length of time to mute the user.

### What do you need to do?

Change description of command argument to accurately reflect what it does.

**Comment by sital002** [comment]
I would like to work on this issue.
