### ISSUE TITLE
[FEAT] - Fragment the Help Embed

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/Becca-Lyria#319]
# Feature Request

## Is your feature request related to a problem? Please describe:

Discord embed limits include a maximum of 1024 characters per embed *field*.

## Describe the solution you'd like

To avoid hitting that limit as more commands are added, let's modify the help command to add a field for every 20 commands.

**Comment by Vyvy-vi** [comment]
Perhaps you can use https://www.npmjs.com/package/discord.js-menu to make help command in a page-ified form?

**Comment by nhcarrigan** [comment]
I've got the code in another repository for paginating embeds, so this could be done from scratch rather than relying on an additional package.

**Comment by Vyvy-vi** [comment]
Oh great 👍
