### ISSUE TITLE
[FEAT]: Message Link in messageUpdated logs

### ISSUE THREAD

**Issue by Vyvy-vi** [nhcarrigan/Becca-Lyria#439]
# Feature Request

## Is your feature request related to a problem? Please describe:

Not a very large problem, but it would be a neat feature to have.
The current logs do provide the message content and the Author but in many cases moderators might need additional context regarding the chat, to decide whether some messages were in violation or not.
Scrolling back all the way to the message might be time-consuming and slightly tiresome task for the moderators. 

## Describe the solution you'd like

It would be great, if we use `message.url` to link to the updated message in the log embed.

## Additional context
We could perhaps link to the message in the embed title or add a new field for the URL?
Screenshot of current messageUpdated log embed: 
![Screenshot 2020-12-29 at 3 49 53 PM](https://user-images.githubusercontent.com/62864373/103276821-93c26700-49ed-11eb-96df-57d38e7bf62f.png)

Would I like to work on this issue:
- [x] yes :)

**Comment by nhcarrigan** [comment]
Thank you for the suggestion! I've gone ahead and opened this up for contributions. 🙂
