### ISSUE TITLE
[FEAT] - Update Contributors command

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/Becca-Lyria#458]
# Feature Request

## Is your feature request related to a problem? Please describe:

As our contributor base grows, we risk hitting embed limits with the `contributors` command.

## Describe the solution you'd like

This command should be refactored to do the following:
- Set the `title` to "Thanks to these wonderful contributors:"
- Set the `description` to a comma separated list of contributor names.
- Set the `footer` to a link to the repository README.

**Comment by Vyvy-vi** [comment]
I'd like to work on this :)

**Comment by nhcarrigan** [comment]
Sure thing!

**Comment by Vyvy-vi** [comment]
the footer link isn't a hyperlink
should I add this the link in the description, or is the footer fine?

**Comment by Vyvy-vi** [comment]
Which one is more prefered
![embed with link in footer doesn't hyperlink](https://user-images.githubusercontent.com/62864373/103895827-041c6700-5117-11eb-9d0e-30521f8676da.png)

**Comment by nhcarrigan** [comment]
The footer link looks nice - I like it.
